vich_uploader:
    db_driver: orm

    mappings:
       legend_image:
           uri_prefix: /images/legends
           upload_destination: '%kernel.project_dir%/public/images/legends'
       icon_image:
           uri_prefix: /images/icons
           upload_destination: '%kernel.project_dir%/public/images/icons'           